### ISSUE TITLE
[SCRUM] Week of April 2

### ISSUE THREAD

**Issue by PragyaJollySingh** [yeskunall/pproval.app#34]
Provides a platform for each team member to add comments with their own contributions.

Questions to be answered:

1. What have I done this week?
    1. Created a login page 
     2. Made sure the login page directs to the proper editor page if they are an editor
     3. Make sure the login page directs to the proper submitter page if the user is a submitter
     4. Wrote test classes for the user 
     4. Wrote test classes for Articles

2. What will I do next week?
This project is over
3. What is holding me back? (if applicable)Certain files are missing due to alterations that I needed and the same with the classes. Hence why I had to make my own login system. Miss communication and I should have pushed my code before the night before as I didn't realize I was going to have merge issues. 

__NOTE__: Must be done before the end date

**Comment by ryanribeiro** [comment]
1. What have I don this week?
- Worked on getting master up to date with the model for Submitter in order to resolve merge conflicts
- Setup submission/view for Submitter (submission has problems)

2. What will I do next week?
N/A

3. What is holding me back?
- Struggling with basic understanding of controllers/views/repository
- Process being followed, but stuff is moving along too slow

**Comment by yeskunall** [comment]
1. What have I done this week?

-  Setup default users (and roles) #29

2. What will I do next week?

N/A

3. What held me back this time around?

- Too many changes. Group members dropping out. No clear project direction up until we got feedback for milestone 2, even after which team members seemed unclear on basic `git` stuff, so that slowed all of us down
